# Generated by Django 4.2.8 on 2023-12-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'address')},
        ),
    ]
